=== adangel/pmd-regression-tester/config/projectlist_1_2_0.xsd
<?xml version="1.0" ?>
<!-- version 1.1.0 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="projectlist">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="description" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="project" type="project" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="project">
    <xs:sequence>
      <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
      <xs:element name="type" minOccurs="1" maxOccurs="1">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="git"/>
            <xs:enumeration value="hg"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="connection" type="xs:string" minOccurs="1" maxOccurs="1"/>
      <xs:element name="webview-url" type="xs:string" minOccurs="0" maxOccurs="1"/>
      <xs:element name="tag" type="xs:string" minOccurs="0" maxOccurs="1"/>
      <xs:element name="src-subpath" type="xs:string" minOccurs="0" maxOccurs="1" default=".">
        <xs:annotation>
          <xs:documentation>
            Value of the -dir option for the PMD run.
            The value must be a directory path relative to the root directory of the clone.
            Defaults to just '.', ie the entire directory.
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="exclude-pattern" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="build-command" type="xs:string" minOccurs="0" maxOccurs="1"/>
      <xs:element name="auxclasspath-command" type="xs:string" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== adangel/pmd-regression-tester/test/resources/integration_test_runner/project-list.xml
<?xml version="1.0"?>

<projectlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="projectlist_1_2_0.xsd">
  <description>Standard Projects</description>

  <project>
    <name>checkstyle</name>
    <type>git</type>
    <connection>https://github.com/checkstyle/checkstyle</connection>
    <tag>checkstyle-8.10</tag>
    <exclude-pattern>**/src/test/resources-noncompilable/**/*</exclude-pattern>
    <exclude-pattern>**/src/test/resources/**/*</exclude-pattern>
  </project>

<!-- The base pmd_releases_6.6.0-baseline.zip contains also spring-framework
     which is skipped in that integration test -->
<!--
  <project>
    <name>spring-framework</name>
    <type>git</type>
    <connection>https://github.com/spring-projects/spring-framework</connection>
    <tag>v5.0.6.RELEASE</tag>
  </project>
-->
</projectlist>

=== adangel/pmd-regression-tester/test/resources/integration_test_runner/project-list-with-apex.xml
<?xml version="1.0"?>

<projectlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="projectlist_1_2_0.xsd">
  <description>Standard Projects</description>

  <project>
    <name>checkstyle</name>
    <type>git</type>
    <connection>https://github.com/checkstyle/checkstyle</connection>
    <tag>checkstyle-9.1</tag>

    <exclude-pattern>.*/target/test-classes/com/puppycrawl/tools/checkstyle/.*</exclude-pattern>
    <exclude-pattern>.*/target/generated-sources/.*</exclude-pattern>
    <exclude-pattern>.*/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/javaparser/InputJavaParserNoFreezeOnDeeplyNestedLambdas.java</exclude-pattern>

    <build-command><![CDATA[#!/usr/bin/env bash
if test -e classpath.txt; then
  exit
fi

set -e

# Make sure to use java11. This is already installed by setup-java.
export JAVA_HOME=${HOME}/openjdk11
export PATH=$JAVA_HOME/bin:$PATH

mvn test-compile -B
mvn dependency:build-classpath -DincludeScope=test -Dmdep.outputFile=classpath.txt -B
]]></build-command>
    <auxclasspath-command>echo -n "$(pwd)/target/classes:$(pwd)/target/test-classes:"; cat classpath.txt</auxclasspath-command>
  </project>

<!-- The base pmd_releases_6.40.0-baseline.zip contains also spring-framework
     which is skipped in that integration test -->
<!--
  <project>
    <name>spring-framework</name>
    <type>git</type>
    <connection>https://github.com/spring-projects/spring-framework</connection>
    <tag>v5.3.13</tag>
  </project>
-->

<!-- The base pmd_releases_6.40.0-baseline.zip does not contain Schedul-o-matic-9000.
     All the found violation will appear as new. -->
  <project>
    <name>Schedul-o-matic-9000</name>
    <type>git</type>
    <connection>https://github.com/SalesforceLabs/Schedul-o-matic-9000</connection>
    <tag>6b1229ba43b38931fbbab5924bc9b9611d19a786</tag>
  </project>

</projectlist>

=== adangel/pmd-regression-tester/test/resources/project_diff_report/project-list.xml
<?xml version="1.0"?>

<projectlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="projectlist_1_2_0.xsd">
  <description>Standard Projects</description>

  <project>
    <name>checkstyle</name>
    <type>git</type>
    <connection>https://github.com/checkstyle/checkstyle</connection>
    <tag>checkstyle-8.10</tag>
    <exclude-pattern>**/src/test/resources-noncompilable/**/*</exclude-pattern>
    <exclude-pattern>**/src/test/resources/**/*</exclude-pattern>
    <build-command>mvn test-compile -B</build-command>
    <auxclasspath-command>echo -n "$(pwd)/target/classes:"</auxclasspath-command>
  </project>

  <project>
    <name>openjdk10</name>
    <type>hg</type>
    <connection>http://hg.openjdk.java.net/jdk10/jdk10/jdk</connection>
    <webview-url>http://hg.openjdk.java.net/jdk10/jdk10/jdk/file/777356696811</webview-url>
  </project>

  <project>
    <name>spring-framework</name>
    <type>git</type>
    <connection>https://github.com/spring-projects/spring-framework</connection>
    <webview-url>https://github.com/spring-projects/spring-framework/tree/v5.0.6.RELEASE</webview-url>
    <tag>v5.0.6.RELEASE</tag>
  </project>

</projectlist>

=== adangel/pmd-regression-tester/test/resources/integration_test_project_builder/project-list_commit_sha1.xml
<?xml version="1.0"?>

<projectlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="projectlist_1_2_0.xsd">
  <description>Standard Projects</description>

  <project>
    <name>Schedul-o-matic-9000</name>
    <type>git</type>
    <connection>https://github.com/SalesforceLabs/Schedul-o-matic-9000</connection>
    <tag>6b1229ba43b38931fbbab5924bc9b9611d19a786</tag>
  </project>

  <project>
    <name>fflib-apex-common</name>
    <type>git</type>
    <connection>https://github.com/apex-enterprise-patterns/fflib-apex-common</connection>
    <tag>7e0891efb86d23de62811af56d87d0959082a322</tag>
  </project>

</projectlist>

=== adangel/pmd-regression-tester/test/resources/project_builder/project-list.xml
<?xml version="1.0"?>

<projectlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="projectlist_1_2_0.xsd">
  <description>Standard Projects</description>

  <project>
    <name>checkstyle</name>
    <type>git</type>
    <connection>https://github.com/checkstyle/checkstyle</connection>
    <tag>checkstyle-9.1</tag>
    <exclude-pattern>.*/target/test-classes/com/puppycrawl/tools/checkstyle/.*</exclude-pattern>
    <exclude-pattern>.*/target/generated-sources/.*</exclude-pattern>
    <exclude-pattern>.*/src/test/resources-noncompilable/com/puppycrawl/tools/checkstyle/javaparser/InputJavaParserNoFreezeOnDeeplyNestedLambdas.java</exclude-pattern>
    <build-command>mvn test-compile -B</build-command>
    <auxclasspath-command><![CDATA[#!/usr/bin/env bash
echo -n "$(pwd)/target/classes:"
        ]]></auxclasspath-command>
  </project>

  <project>
    <name>spring-framework</name>
    <type>git</type>
    <connection>https://github.com/spring-projects/spring-framework</connection>
    <webview-url>https://github.com/spring-projects/spring-framework/tree/v5.3.13</webview-url>
    <tag>v5.3.13</tag>
  </project>

</projectlist>
