=== adangel/pmd-regression-tester/config/projectlist_1_0_0.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="projectlist">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="description" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="project" type="project" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="project">
    <xs:sequence>
      <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
      <xs:element name="type" type="type" minOccurs="1" maxOccurs="1"/>
      <xs:element name="connection" type="xs:string" minOccurs="1" maxOccurs="1"/>
      <xs:element name="webview-url" type="xs:string" minOccurs="1" maxOccurs="1">
      <xs:element name="tag" type="xs:string" minOccurs="0" maxOccurs="1"/>
      <xs:element name="exclude-pattern" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="type">
    <xs:restriction base="xs:token">
      <xs:enumeration value="git"/>
      <xs:enumeration value="hg"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== adangel/pmd-regression-tester/test/resources/project-test.xml
<?xml version="1.0"?>

<projectlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="projectlist_1_0_0.xsd">
  <description>Standard Projects</description>

  <project>
    <name>test_repo</name>
    <type>git</type>
    <connection>test/resources/repositories/test_repo</connection>
  </project>

  <project>
    <name>pmd</name>
    <type>git</type>
    <connection>https://github.com/pmd/pmd</connection>
  </project>
</projectlist>
